CLUSTAL multiple sequence alignment by MUSCLE (3.8)


AJ417565.2          ---------------------AACTCCAAGTCAGATATCCGAACTCTGAATATCAA-CTG
NM_012675.3         -----------------------CACCAAGGGACCAGCCAGGAGGGAGAACAGCAA-CTC
M13049.1            ----AGAAGCTCCTCAGCGAGGACAGCAAGGGACTAGCCAGGAGGGAGAACAGAAA-CTC
NM_001082263.1      -----AAGCTCCCTCAGTGAGGACAC--GGGCACCAGCTAGGAGGGAGAGCAGCAA-CTC
NM_173966.3         AACAGAAGCTCCCAGAGCGGGGACACCAGGGGACCAGCCAGGAGAGAGACAAGCAG-CTG
NM_001024860.1      -------------------GGGACACCAGGGGACCAGCCAAGAGAGAGACAAGCAG-CTG
NM_214022.1         ----------CCCAGAGTGAGGACACCAGGGGACCAGCCAGGAGAGAGACAAGCCATCTC
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         AGCAGACGCTCCCTCAGCAAGGACAGCAGAGGACCAGCTAAGAGGGAGAGAAGCAA-CTA
NM_001081819.2      --------------------------------CCCAGCTGGACTTGAG------------
                                                                                

AJ417565.2          CAGGAGCT--------------------------------------GCAATCAGAACGAC
NM_012675.3         CAGAACACCCTGGTACTAA-CTCCCAGAAAA-------GCAAGCAACCAGCCAGGCAGGT
M13049.1            CAGAACATCCTGGAAATAG-CTCCCAGAAAA-------GCAAGCAGCCAACCAGGCAGGT
NM_001082263.1      CAGGCTACCCCGGCAGTAA-CTCCCAGACGCCGCCCCGCCAGACAAGCTGCCAGCCGGTG
NM_173966.3         CAGAACCCCCTGGAGATAACCTCCCAGACAACACACCCCCGAG-AGACAGCCAGGCAACT
NM_001024860.1      CAGAACCCCCTGGAGATAACCTCCCAGACAACACACCCCCGAG-AGACAGCCAGGCAACT
NM_214022.1         CAGGACCCCCTAGAAATAACCTCTCAGAAGACACACCCCCGAACAGGCAGCCGGAC-GAC
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         CAGACCCCCCCTGAAAACAACCCTCAGACGCCACATCCCCTGACAAGCTGCCAGGCAGGT
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          TA-------------------------------------------------------GAT
NM_012675.3         TC-----CGTCCCTCTCATACACTGGCCCGAGGCAACACATC------------------
M13049.1            TC-----TGTCCCTTTCACTCACTGGCCCAAGGCGCCACATC------------------
NM_001082263.1      TGCCGTCTTCCTCTCTCACGCACCAGCCCCCGGTTCCACCACCT----------------
NM_173966.3         TG----CTCTCTCTCACATACCCTGCCACAAGGCTCTCCTGTCTCCCGTCTGGACTTGAA
NM_001024860.1      TG------CTCTCTCATACACCCTGCCACAAGGCTCTCCTGTCTCCCGTCTGGACTTGGA
NM_214022.1         TC-----TCTCCCTCTCACACGCTGCCCCGGGGCGCCACCATCTCCCAGCTGGACCTGAG
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         TC-----TCTTCCTCTCACATACTGACCCACGGCTCCACCCTCT----------------
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          TTCTCCTGAAGGACTAACTACTAGACGACTCAGAG-ATGGCCAGTGACAGTCAGGTGGTA
NM_012675.3         TCCCTCCGGAAAGGACACCATGAGC--ACGGAAAGCATGATCCGAGAT------GTGGAA
M13049.1            TCCCTCCAGAAAAGACACCATGAGC--ACAGAAAGCATGATCCGCGAC------GTGGAA
NM_001082263.1      -CCCTCTGGAGAGAGCGCCATGAGC--ACTGAGAGTATGATCCGGGAC------GTCGAG
NM_173966.3         CCCTTCTGAAAAAGACACCATGAGC--ACCAAAAGCATGATCCGGGAT------GTGGAG
NM_001024860.1      TCCTTCTGAAAAAGACACCATGAGC--ACCAAAAGCATGATCCGGGAT------GTGGAG
NM_214022.1         CCCCTCTGAAAAAGACACCATGAGC--ACTGAGAGCATGATCCGAGAC------GTGGAG
NM_001003244.4      -------------------ATGAGC--ACTGAAAGCATGATCCGGGAC------GTGGAG
NM_000594.4         CTCCCCTGGAAAGGACACCATGAGC--ACTGAAAGCATGATCCGGGAC------GTGGAG
NM_001081819.2      CCCCTCTGGAAAGGACATCATGAGC--ACTGAAAGCATGATCCGAGAT------GTGGAG
                                       *  **   **  * ** ***  * * **       ** *  

AJ417565.2          TTGGATGTGGACGGACCCCGGGTGACGATCGTACGAGAGAAGGCCTCGTGGTCTTCTTCA
NM_012675.3         CTGGCAGAGGAGGCGCTCCCCAAAAAGAT--------GGGGGGCCTCCAGAACTCCAGGC
M13049.1            CTGGCAGAAGAGGCACTCCCCCAAAAGAT--------GGGGGGCTTCCAGAACTCCAGGC
NM_001082263.1      CTGGCGGAGGGGCCGCTCCCCAAGAAGGC--------AGGGGGGCCCCAGGGCTCCAAGC
NM_173966.3         CTGGCGGAGGAGGTGCTCTCCGAGAAAGC--------AGGGGGCCCCCAGGGCTCCAGAA
NM_001024860.1      CTGGCGGAGGAGGTGCTCTCCAACAAAGC--------AGGGGGCCCCCAGGGCTCCAGAA
NM_214022.1         CTGGCGGAGGAGGCGCTCGCCAAGAAGGC--------CGGGGGCCCCCAGGGCTCCAGGA
NM_001003244.4      CTGGCCGAGGAGCCGCTCCCCAAGAAGGC--------GGGGGGCCCCCCGGGCTCCAGAA
NM_000594.4         CTGGCCGAGGAGGCGCTCCCCAAGAAGAC--------AGGGGGGCCCCAGGGCTCCAGGC
NM_001081819.2      CTGGCAGAGGAGGAGCTCGCCAAGAAGGC--------AGGGGGCCCCCAGGGCTCCAGAC
                     ***  *  *     * *      *             *  **   *  *  ** *    

AJ417565.2          GGAGTTTGG-----AGAACCTGTGGAGTCCTTCTCGCCGT--GGCTCTCTGCGCTGCCGC
NM_012675.3         GGTGTCTGTGCCTCAGCCTCTTCTCATTCCTGCTCGTGGCGGGGGCCACCACGCT----C
M13049.1            GGTGCCTATGTCTCAGCCTCTTCTCATTCCTGCTTGTGGCAGGGGCCACCACGCT----C
NM_001082263.1      GCTGCCTCTGCCTCAGCCTCTTCTCTTTCCTGCTCGTGGCTGGAGCCACCACGCT----C
NM_173966.3         GTTGCTTGTGCCTCAGCCTCTTCTCCTTCCTCCTGGTTGCAGGAGCCACCACGCT----C
NM_001024860.1      GTTGCTGGTGCCTCAGCCTCTTCTCCTTCCTCCTGGTTGCAGGAGCCACCACGCT----C
NM_214022.1         GGTGCCTGTGCCTCAGCCTCTTCTCCTTCCTCCTGGTCGCAGGAGCCACCACGCT----C
NM_001003244.4      GGTGCTTCTGCCTCAGCCTCTTCTCCTTCCTCCTCGTCGCAGGGGCCACCACACT----C
NM_000594.4         GGTGCTTGTTCCTCAGCCTCTTCTCCTTCCTGATCGTGGCAGGCGCCACCACGCT----C
NM_001081819.2      GGTGCTTGTGCCTCAGCCTCTTCTCCTTCCTCCTTGTCGCAGGAGCCACCACGCT----C
                    *  *          **   **      ****  * *  *   *   * *  * **    *

AJ417565.2          CGCTGTCTGCTTTTCTCAAAACAAGACGCACAACAAA--------------CCAGACGAG
NM_012675.3         TTCTGTCTACTGAACTTCGGGGTGATCGGTCCCAACAAGGAGGAGAAGTTCCCAAATGGG
M13049.1            TTCTGTCTACTGAACTTCGGGGTGATCGGTCCCCAAAGGGATGAGAAGTTCCCAAATGGC
NM_001082263.1      TTCTGCCTGCTGCACTTCAGGGTGATCGGCCCTCAGGAGGAAG---AGTCCCCAAACAAC
NM_173966.3         TTCTGCCTGCTGCACTTCGGGGTAATCGGCCCCCAGAGGGAAGAGCAGTCCCCAGGTGGC
NM_001024860.1      TTCTGCCTGCTGCACTTCGGGGTAATCGGCCCCCAGAGGGAAGAGCAGTCCCCAGCTGGC
NM_214022.1         TTCTGCCTACTGCACTTCGAGGTTATCGGCCCCCAGAAGGAAG---AGTTTCCAGCTGGC
NM_001003244.4      TTCTGCCTGCTGCACTTTGGAGTGATCGGCCCCCAGAGGGAAG---AGCTCCCAAATGGC
NM_000594.4         TTCTGCCTGCTGCACTTTGGAGTGATCGGCCCCCAGAGGGAAG---AGTTCCCCAGGGAC
NM_001081819.2      TTCTGCCTGCTGCACTTTGGGGTGATCGGCCCCCAGAGGGAAGAGCAGTTACCGAATGCC
                      *** ** **   **          **  *   *                **       

AJ417565.2          ACCCAAGAAATCAAGCAC---------------TCTCTCAGGCAGATTTCCCAGACTGCG
NM_012675.3         CTCCCTCTCATCAGTTCCATGGCCCAGACCCTCACACTCAGATCATCTTCTCAAAACTCG
M13049.1            CTCCCTCTCATCAGTTCTATGGCCCAGACCCTCACACTCAGATCATCTTCTCAAAATTCG
NM_001082263.1      CTCCATCTAGTCAACCCTGTGGCCCAGATGGTCACCCTCAGATCAGCTTCTCGGGCCCTG
NM_173966.3         CCCTCCATCAACAGCCCTCTGGTTCAA------ACACTCAGGTCCTCTTCTCAAGCCTCA
NM_001024860.1      CCCTCCTTCAACAGGCCTCTGGTTCAG------ACACTCAGGTCATCTTCTCAAGCCTCA
NM_214022.1         CCCTTGAGCATCAACCCTCTGGCCCAA------GGACTCAGATCATCGTCTCAAACCTCA
NM_001003244.4      CTCCAACTAATCAGCCCTCTTGCCCAG------ACAGTCAAATCATCTTCTCGAACCCCA
NM_000594.4         CTCTCTCTAATCAGCCCTCTGGCCCAG------GCAGTCAGATCATCTTCTCGAACCCCG
NM_001081819.2      TTCCAGTCAATCAACCCTCTGGCCCAG------ACACTCAGATCATCTTCTCGAACCCCA
                      *        **                        ***        ** *        

AJ417565.2          AAGGCTGCGATCCATCTCTCAGGTCACTACAACCCGCAGGTTTCGAGCGTATCTATGCAG
NM_012675.3         AGTGACAAG-CCCGTAGCCCACGTCGTAGCAAACCACCAAGCGGAGGAGCAGC--TGGAG
M13049.1            AGTGACAAG-CCTGTAGCCCACGTCGTAGCAAACCACCAAGTGGAGGAGCAGC--TGGAG
NM_001082263.1      AGTGACAAG-CCTCTAGCCCACGTAGTAGCAAACCCGCAAGTGGAGGGCCAGC--TCCAG
NM_173966.3         AGTAACAAG-CCGGTAGCCCACGTTGTAGCCGACATCAACTCTCCGGGGCAGC--TCCGG
NM_001024860.1      AATAACAAG-CCGGTAGCCCACGTTGTAGCCAACATCAGCGCTCCGGGGCAGC--TCCGA
NM_214022.1         ---GATAAG-CCCGTCGCCCACGTTGTAGCCAATGTCAAAGCCGAGGGACAGC--TCCAA
NM_001003244.4      AGTGACAAG-CCAGTAGCTCATGTTGTAGCAAACCCCGAAGCTGAGGGGCAGC--TCCAG
NM_000594.4         AGTGACAAG-CCTGTAGCCCATGTTGTAGCAAACCCTCAAGCTGAGGGGCAGC--TCCAG
NM_001081819.2      AGTGACAAG-CCTGTAGCCCATGTTGTAGCAAACCCCCAAGCCGAGGGGCAGC--TCCAG
                            *  *  *  * ** **     *                *   * *  *    

AJ417565.2          TGGTTCGACAACGCAGACCA--GTCCTTCTCTTCA--GGCTTGAAACTGGAGGACAACGA
NM_012675.3         TGGCTGAGCCA-GCGTGCCAACGCCCTCCTGGCCAATGGCATGGATCTCAAAGACAACCA
M13049.1            TGGCTGAGCCA-GCGCGCCAACGCCCTCCTGGCCAACGGCATGGATCTCAAAGACAACCA
NM_001082263.1      TGGCTGAGCCA-GCGTGCGAACGCCCTGCTGGCCAACGGCATGAAGCTCACGGACAACCA
NM_173966.3         TGGTGGGACTC-GTATGCCAATGCCCTCATGGCCAACGGTGTGAAGCTGGAAGACAACCA
NM_001024860.1      TGGGGGGACTC-GTATGCCAATGCCCTCATGGCCAACGGCGTGGAGCTGAAAGACAACCA
NM_214022.1         TGGCAGAGTGG-GTATGCCAATGCCCTCCTGGCCAACGGCGTGAAGCTGAAAGACAACCA
NM_001003244.4      TGGCTGAGCCG-ACGTGCCAATGCCCTCCTGGCCAACGGCGTGGAGCTGACAGACAACCA
NM_000594.4         TGGCTGAACCG-CCGGGCCAATGCCCTCCTGGCCAATGGCGTGGAGCTGAGAGATAACCA
NM_001081819.2      TGGCTGAGTGG-GCGTGCAAATGCCCTCCTGGCCAATGGCGTGAAGCTGACAGACAACCA
                    ***              * *  * ***  *   **  **  ** * **    ** *** *

AJ417565.2          GATCAAGATTCTCCGCGACGGCCTCTACTTCGTCTACAGCCAGGCCTCGTACCGTCTGCT
NM_012675.3         ACTGGTGGTACCAGCAGATGGGCTGTACCTTATCTACTCCCAGGTT------------CT
M13049.1            ACTAGTGGTGCCAGCCGATGGGTTGTACCTTGTCTACTCCCAGGTT------------CT
NM_001082263.1      GCTGGTGGTGCCGGCCGACGGGCTGTACCTCATCTACTCCCAGGTT------------CT
NM_173966.3         GCTGGTGGTGCCTGCTGACGGGCTTTACCTCATCTACTCACAGGTC------------CT
NM_001024860.1      GCTGGTGGTGCCCACTGACGGGCTTTACCTCATCTACTCGCAGGTC------------CT
NM_214022.1         GCTGGTGGTGCCGACAGATGGGCTGTACCTCATCTACTCCCAGGTC------------CT
NM_001003244.4      GCTGATAGTGCCGTCAGATGGGTTGTACCTCATCTACTCCCAGGTC------------CT
NM_000594.4         GCTGGTGGTGCCATCAGAGGGCCTGTACCTCATCTACTCCCAGGTC------------CT
NM_001081819.2      GCTGGTGGTACCATTGGATGGGCTGTACCTCATCTACTCCCAGGTC------------CT
                      *     * *     ** **  * *** *  *****   ****              **

AJ417565.2          ATGTAAAGCCGAGGGCGACGAGACCGAGGGCGAGGTGATGCACATGAGCCACAAAGTGTC
NM_012675.3         CTTCAAGGGACAAGGCTGCC---CCGACTACG------TGCTCCTCACCCACACCGTCAG
M13049.1            CTTCAAGGGACAAGGCTGCC---CCGACTACG------TGCTCCTCACCCACACCGTCAG
NM_001082263.1      CTTCAGCGGTCAAGGCTGCCGCT---CCTACG------TGCTCCTCACTCACACTGTCAG
NM_173966.3         CTTCAGGGGCCAAGGCTGCCCTTCCACCCCCT------TGTTCCTCACCCACACCATCAG
NM_001024860.1      CTTCAGGGGCCACGGCTGCCCTTCCACCCCCT------TGTTCCTCACCCACACCATCAG
NM_214022.1         CTTCAGGGGCCAAGGCTGCCCTTCCACCAACG------TTTTCCTCACTCACACCATCAG
NM_001003244.4      CTTCAAGGGCCAAGGGTGCCCTTCCACCCATG------TGCTCCTCACCCACACCATCAG
NM_000594.4         CTTCAAGGGCCAAGGCTGCCCCTCCACCCATG------TGCTCCTCACCCACACCATCAG
NM_001081819.2      CTTCAAAGGCCAAGGCTGCCCTTCCACCCATG------TGCTCCTCACCCACACCATCAG
                     *  *  *   * **   *                   *   * * *  ****   *   

AJ417565.2          TCGCTGGTCTGACTCTTACAGCTCATGGAAGCCG--TTGCTGAGCGCCACCAGATCGGCC
NM_012675.3         CCGATTTGCCATTTCATAC--CAGGAGAAAGTCAGCCTCCTCTCTGCCATCAAGAGCCCT
M13049.1            CCGATTTGCTATCTCATAC--CAGGAGAAAGTCAACCTCCTCTCTGCCGTCAAGAGCCCC
NM_001082263.1      CCGCTTCGCCGTCTCCTAC--CCGAACAAGGTCAACCTCCTCTCTGCCATCAAGAGCCCC
NM_173966.3         CCGCATTGCAGTCTCCTAC--CAGACCAAGGTCAACATCCTGTCTGCCATCAAGAGCCCT
NM_001024860.1      CCGCATTGCAGTCTCCTAC--CAGACCAAGGTCAACATCCTCTCTGCCATCAAGAGCCCT
NM_214022.1         CCGCATCGCCGTCTCCTAC--CAGACCAAGGTCAACCTCCTCTCTGCCATCAAGAGCCCT
NM_001003244.4      CCGCTTCGCCGTCTCCTAC--CAGACAAAGGTCAACCTACTCTCTGCCATCAAGAGCCCT
NM_000594.4         CCGCATCGCCGTCTCCTAC--CAGACCAAGGTCAACCTCCTCTCTGCCATCAAGAGCCCC
NM_001081819.2      CCGCTTAGCTGTCTCCTAC--CCGTCCAAGGTCAACCTCCTCTCTGCCATCAAGAGCCCT
                     **     *    ** ***  *      * * *    * **    ***  **      * 

AJ417565.2          TGC---AAGAAAACAACCGAAGAGTACCAG---AAATACTGGTACGGCGCCGTCTACCTC
NM_012675.3         TGCCCTAAGGACACCCCTGAGGGAGCTGAGCTCAAGCCCTGGTATGAGCCCATGTACCTG
M13049.1            TGCCCCAAGGACACCCCTGAGGGGGCTGAGCTCAAACCCTGGTATGAACCCATATACCTG
NM_001082263.1      TGCCACCGGGAGACCCCCGAGGAGGCTGAGCCCATGGCCTGGTACGAGCCCATCTACCTG
NM_173966.3         TGCCACAGGGAGACCCCAGAGTGGGCTGAGGCCAAGCCCTGGTATGAACCCATCTACCAG
NM_001024860.1      TGCCACAGGGAGACCCTAGAGGGGGCTGAGGCCAAGCCCTGGTACGAACCCATCTACCAG
NM_214022.1         TGCCAGAGGGAGACCCCCGAGGGGGCCGAGGCCAAGCCCTGGTACGAACCCATCTACCTG
NM_001003244.4      TGCCAAAGGGAGACCCCAGAGGGGACCGAGGCCAAGCCCTGGTACGAGCCCATCTACCTG
NM_000594.4         TGCCAGAGGGAGACCCCAGAGGGGGCTGAGGCCAAGCCCTGGTATGAGCCCATCTATCTG
NM_001081819.2      TGCCACACGGAGTCCCCAGAGCAGGCTGAAGCCAAGCCCTGGTATGAGCCCATCTACCTG
                    ***     * *  *    **        *    *    ****** *   ** * ** *  

AJ417565.2          GGGGCCGCGTTCAACCTGAAGGCCGGAGACCGACTGCGCACCGTCATGGACGAGAAGCTG
NM_012675.3         GGAGGAGTCTTCCAGCTGGAGAAGGGGGACCTGCTCAGCGCTGAGGTCAAC---------
M13049.1            GGAGGAGTCTTCCAGCTGGAGAAGGGGGACCAACTCAGCGCTGAGGTCAAT---------
NM_001082263.1      GGCGGCGTCTTCCAGTTGGAGAAGGGTGACCGGCTCAGCACCGAGGTCAAC---------
NM_173966.3         GGAGGAGTCTTCCAGCTGGAGAAGGGAGATCGCCTCAGTGCTGAGATCAAC---------
NM_001024860.1      GGAGGGGTCTTCCAGCTGGAGAAGGGAGATCGCCTCAGTGCTGAGATCAAC---------
NM_214022.1         GGAGGGGTCTTCCAGCTGGAGAAGGATGATCGACTCAGTGCCGAGATCAAC---------
NM_001003244.4      GGAGGGGTCTTCCAACTGGAGAAGGGTGATCGACTCAGCGCTGAGATCAAT---------
NM_000594.4         GGAGGGGTCTTCCAGCTGGAGAAGGGTGACCGACTCAGCGCTGAGATCAAT---------
NM_001081819.2      GGAGGAGTCTTCCAGCTGGAGAAGGGTGATCAACTCAGCGCTGAGATCAAT---------
                    ** *  *  *** *  ** **   *  ** *  **  *  * *   *  *          

AJ417565.2          CTGCCCAAAG---TGGAGAGCGCCGG---CGGGAAAACCTTCTTCGGAACGTTCTCCTTA
NM_012675.3         CTGCCCAAGTACTTAGACATCACGGAGTCCGGGCAGGTCTACTTTGGAGTCATTGCTCTG
M13049.1            CTGCCCAAGTACTTAGACTTTGCGGAGTCCGGGCAGGTCTACTTTAGAGTCATTGCTCTG
NM_001082263.1      CAGCCTGAGTACCTGGACCTTGCCGAGTCCGGGCAGGTCTACTTTGGGATCATTGCCCTG
NM_173966.3         CTGCCGGACTACCTGGACTATGCCGAGTCTGGGCAGGTCTACTTTGGGATCATCGCCCTG
NM_001024860.1      CTGCCGGAATACCTGGACTATGCCGAGTCTGGGCAGGTCTACTTTGGGATCATCGCCCTG
NM_214022.1         CTGCCCGACTATCTGGACTTTGCTGAATCTGGGCAGGTCTATTTTGGGATCATTGCCCTG
NM_001003244.4      CTGCCTAACTATCTGGACTTTGCCGAGTCCGGGCAGGTGTACTTTGGAATCATTGCCCTG
NM_000594.4         CGGCCCGACTATCTCGACTTTGCCGAGTCTGGGCAGGTCTACTTTGGGATCATTGCCCTG
NM_001081819.2      CAGCCCAACTATCTCGACTTTGCGGAGTCCGGGCAGGTCTACTTTGGGATCATTGCCCTG
                    * ***  *     * **     * *     *** *    *  **  *     *  *  * 

AJ417565.2          TAAAGATCTAAA------------------------------------------------
NM_012675.3         TGAGGCGACTGGCGTGTTCATCCGTTCTCTACCCAGCCCCTGTCCCCGACTCTGACCCCC
M13049.1            TGAAGGGAATGG-GTGTTCATCCATTCTCTACCCAGCCCCCACTCT--------GACCCC
NM_001082263.1      TGAGGGGACTGA-----CCACCACTCCTCC------CCCTC---------------TCCC
NM_173966.3         TGAGGGTGCAGG-----ACATGCA------------TCTTC---------------TCCC
NM_001024860.1      TGAGGGCGCAGG-----ACATGCA------------TCCTC---------------TCCC
NM_214022.1         TGAGGGGGCAGG-----ACATCCG------------TTCCC---------------TCCC
NM_001003244.4      TAAGGGGGTAGG-----ACGTCCATTCTT---------------------------GCCC
NM_000594.4         TGAGGAGGACGA-----ACATCCAACCTTCCCAAACGCCTC---------------CCCT
NM_001081819.2      TGAGGGGG--GT-----ACGTCCG------------TCCTC---------------GCCC
                    * * *                                                       

AJ417565.2          -----------------------------------------AGATTGTCATTTTGGAACT
NM_012675.3         ATTACTCTGACCCCTTTATCG-TCTACTCCTCAGAGCCCCCAATCTGTGTCCTTCTAACT
M13049.1            TTTACTCTGACCCCTTTATTG-TCTACTCCTCAGAGCCCCCAGTCTGTGTCCTTCTAACT
NM_001082263.1      ---ACCCCAGCCCCCTCACTC-TGGGCGCCCTCAGCCCC-T--CTCATCCTCCTCTAGCT
NM_173966.3         ---ACCTCAGTTACCTTATTA-TTTAATCCTTCAGGCCCTT--CTCATCCCCTTCTGGTT
NM_001024860.1      ---ACCTCAGTTACCTTATTA-TTTACTCCTTCAGACCCTC--CTCATCCCCTTCTGGTT
NM_214022.1         ---CTGTCCATCCCTTTATTATTTTACTCCTTCAGACCC-C--CTCACGTCCTTCTGGTT
NM_001003244.4      ---AAACCGACCCTTTGATCA-CTCACTTCCTCTGACCC----CTCACCCCCTTCAGGCT
NM_000594.4         ---GCCCCAATCCCTTTATTA-CCCCCTCCTTCAGACACC---CTCAACCTCTTCTGGCT
NM_001081819.2      ---ACCTCAATCCCTTTATTA-TCTGCTCCTT----------------------------
                                                                                

AJ417565.2          TTTGCAAGG------------CAGAGCCTGAC----------------TGAAGAACTGTT
NM_012675.3         TAGAAAGGG-AATTGT-GGCTCTGGGTCCAACTCCGGGCTCAGAATTTCCAACAAC---T
M13049.1            TAGAAAGGG-GATTAT-GGCTCAGAGTCCAACTCTGTGCTCAGAGCTTTCAACAAC----
NM_001082263.1      TAGAAACAGAAATGAGGGGCTCAGAATCAGACCTCA------GAATTTTTAAC------A
NM_173966.3         TAGAAAGGG-AATTATGGGCTCAGGGCTGGGCTCCAAGCATCCAACTTTAAACAAC---A
NM_001024860.1      TAGAAAGGG-AATTAGGGGCTCAGGGCTGGGCTCCAAGCGTCCAACTTTAAACAGCTG--
NM_214022.1         TAGAAAGAG-AATGAGGGGCTGGGGACTGGGCTCCAAGCTTAAAACTTTAAACAACAACA
NM_001003244.4      TAGAAAGAG-AATTAAGGGCTCAGGGCTGGACCTCAAGCTTAGAACTTTAAACGAC----
NM_000594.4         CAAAAAGAG-AATTGGGGGCTTAGGGTCGGAACCCAAGCTTAGAACTTTAAGCAACAAGA
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          GTTTTACATTAAAAC---ATACACGCAAATG-----------------------------
NM_012675.3         ACGATGCTCAGAAACACACGAGACGCTGAAGTAGTGGCCTGGATTG-CGGGCTGCTCATG
M13049.1            ----TACTCAGAAACACAAGATGCTGGGACA--GTGACCTGGACTG-TGGGCCTCTCATG
NM_001082263.1      CCACCACTTAGAAACCTGGACCATGGTGGTGT--AGGCCTGCACAGTCAGGGCCCT----
NM_173966.3         GCTACATTTAGAAATTAGGGATGTAGGGAAGT-GAGGCCTGGACAA-CGGGCCACC----
NM_001024860.1      ----CACTTAGAAATTAGGGATGTAGGGAAGT-GAGGCCTGGACAA-CGGGCCACC----
NM_214022.1         GCAACACTTAGAAATCAGGGATTCAGGGATGT-GTGGCCTGGACAA-CCAGGCACT----
NM_001003244.4      -----ACTTAGAAACCTAAGATCCAG----------------------------------
NM_000594.4         CCACCACTTCGAAACCTGGGATTCAGGAATGT-GTGGCCTGCACAG-TGAAGTGCT----
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          AGTTATCAC---TTCAACTCAAATCTTATGCTT---------------------------
NM_012675.3         AGCCGCCACCGGCAAGGATTCCAAT--GGGCTTTCGGAACTCACTGGATCCC-GGAATGT
M13049.1            CACCACCAT---CAAGGACTCAAAT--GGGCTTTCCGAATTCACTGGAGCCT-CGAATGT
NM_001082263.1      GGCCACACC---AAAGCATTCAAACTGAGGCTTCCAGGACTCACTGGGGCCTTCAGAACT
NM_173966.3         AACCACCAT---CAAGGACTGGAACTGGAACTTCCAGAACTCCCTGGGGTCCACAAGCTT
NM_001024860.1      AACCATCAC---CAAGGACTGGAACTGGAACTTCCAGAACTCCCTCGGGTCCACAAGTTT
NM_214022.1         GACCACCAC---CAAGAATTGGAACTGGGGCTTCCAG-ACTCGCTGGGGTCCTTGGGTTT
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         GGCAACCAC---TAAGAATTCAAACTGGGGCCTCCAGAACTCACTGGGGCCTACAGCTTT
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          ------------------------------------------------------------
NM_012675.3         CGATGCCTGAGTGGATCGGGGGAGTGGAGGGGGGAGTGGATCAGGCTGCCTCTGGCTC--
M13049.1            CCATTCCTGAGTTCTGCAAAGGGAGAGTGG----------TCAGGTTGCCTCTGTCTC--
NM_001082263.1      CCATTCTCAGATTGAGCCCGGAACATCCGG-ATGTGGGGACCACGTAGCCGT--GTTCAG
NM_173966.3         GGGTTCCCGGATGCAACCTGGGACACCCAGAATGTGAGGGCCAG---------GGCTCTT
NM_001024860.1      GGGTTCCCGGATGCAACCTGGGACACCCAGAATGCAAGGGCCAG---------GGTTCTT
NM_214022.1         GGATTCCTGGATGCAACCTGGGACATCTGGAATGTGGCTGCCAGGGAAGCTTGGGTTCCA
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         GATCCCT--------------GACATCTGGAATCTGGAGACCAGGGAGCCTTTGGTTCTG
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          ---------------------------GAGGAGATTCC----------------------
NM_012675.3         ----------------ACAAGGCTGCTGAAGATGTCTCAGGCCTCCCTT-----------
M13049.1            -------------AGAATGAGGCTG--GATAAGATCTC----------------------
NM_001082263.1      GCCAGAACCTTCTAGAAGAGCCCTTGAGAGAAGTTGTCACCCAGACCT------------
NM_173966.3         ACCGGAACACTTCGCAACATTCCTT--GAGAAGATCTCACCTAGAACTTGACATGCGTGG
NM_001024860.1      ACCGGAATACTTCGCAACGTTCCTT--GAGAAGATCTCACCTAGAACTTGACATGGGTGG
NM_214022.1         ATCGGAATACTTCAGAACATTCCTT--GAGAAGATTTCACCTCAATCTTGA------TGA
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         GCCAGAATGCTGCAGGACTT-------GAGAAGACCTCACCTAGAAATTGACACAAGTGG
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          ---------------------------TACCATAACAGCTCTAGAAGTGAAAAA------
NM_012675.3         CCTTCCTTCCTTCCCTCCCTCAGAGCTTCCCAGACTGTTCCCTGAGGCACAGCGCCCAGC
M13049.1            -----AGGCCTTCCTACCTTCAGACCTTTCCAGACTCTTCCCTGAGGTGCAATGCACAGC
NM_001082263.1      -----AGGCCTTCCTCTCCTCAGATGTTTCTACACTCTTCTCTGCAATGTGGAGCCCCGC
NM_173966.3         ACTTCAACTCTCCCTTCCTGCCAATGTTTCCAGA--CTCCCCTGAGGTGGGAAGCCCAGC
NM_001024860.1      GCTTCAACTCTCCCTTCCTGCCAGTGTTTCCAGA--TTCCCCTGAGGTGGGAAGCCCAGC
NM_214022.1         CTTTTTAGGCTTCCCTTTCTTCCAATTTTCCAGA--CTTCCCTGGGATGGGGAGCCCAGC
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         ACCTTAGGCCTTCCTCTCTCCAGATGTTTCCAGA--CTTCCTTGAGACACGGAGCCCAGC
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          -------------------------------TTATAAT---------------TAATTTT
NM_012675.3         CTT---CCTTACGGAA-----CCCCCTCTATTTATAATTGCACCTG-------TGACTAT
M13049.1            CTT---CCTCACAGAGCCAGCCCCCCTCTATTTATATTTGCAC----------TTATTAT
NM_001082263.1      CCC---CCGCCCAGGGCAGG-GCCCCTCTATTTATAGTTGCACTGGTGATTATTGATTAT
NM_173966.3         CCC-AACCCCACTGGGCCAA-CTCCCTCTGTTTATGTTTGCACTTG-------TGATTAT
NM_001024860.1      CCC-AACCCCACTGGGCCAA-CTCCCTCTGTTTATGTTTGCACTTA-------TGATTAT
NM_214022.1         CCCAAACCCCACAGGCCAGC-TCCCTCTTATTTATATTTGCACTTG-------GCATTAT
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         CCT---CCCCATGGAGCCAG-CTCCCTCTATTTATGTTTGCACTTG-------TGATTAT
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          TTATGATTTAATGCATATTTATT---------ATAAACGTATTTATTTAA----------
NM_012675.3         TTATTTATTATTTATTATTTATTTATTTGCTTATGAATGTATTTATTTGGAAGGCCGGGG
M13049.1            TTATTATTTATTTATTATTT----------------------------------------
NM_001082263.1      TTATTATTTATTTAATATTTATTTATTTGCCGATGAATGTATTTATTTGGAAGCTCAGCG
NM_173966.3         TTATTATTTATTTATTATTTATTTATTTACTAATGAATGTATTTATTCAGGAGGTCAAGG
NM_001024860.1      TTATTATTTATTTATTATTTATTTATTTACTAATGAATGTATTTATTCAGGAGGTCAAGG
NM_214022.1         TATTTATTTATTTATTTATTATTTATTTACTAGTGAATGTATTTATTCAGGAGGGCGAGG
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         TTATTATTTATTTATTATTTATTTATTTACAGATGAATGTATTTATTTGGGAGACCGGGG
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          --------------------------------TTATTTATTCTATATTTATTGTG-----
NM_012675.3         CGTCCTGGAGGACCCAGCGTTGGGAAGCTGTCTTCAGGCCAACATGTTTTCTGTGAAAAC
M13049.1            ------------------------------------------------------------
NM_001082263.1      CATCCTGGGGTACCCAGCGTAGGA--GCTGCCTTGGTTCTCACACGTTTTCCGTGAAAAC
NM_173966.3         TGTCCTGGGAGACACAAACTAAGG--GCTGCCTTGGCTCAGATGTGTTTTCTGTGAAAAC
NM_001024860.1      TGTCCTGGGAGACACAAACTAAGG--GCTGCCTTGGCTCAGATGTGTTTTCTGTGAAAAC
NM_214022.1         TGTCCTGGGAGACCCAGCATAAGG--GCTGCCTTGGTTCAGATGTGTTTTCTGTGAAAAC
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         TATCCTGGGGGACCCAATGTAGGA--GCTGCCTTGGCTCAGACATGTTTTCCGTGAAAAC
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          ------------------------------------------------------------
NM_012675.3         GGAGCTAAACTACCAGCTATCCCCATCTGGTCCCCCACCCCTGCCTCGTTGCCTCCCCCC
M13049.1            ------------------------------------------------------------
NM_001082263.1      AGAGCAGAACCATGGGTCGATCCCACCTGGCCCCCTG-----GCCCCTGTGCCTCCCTTC
NM_173966.3         GGAGCTGAACTGCAGGTTGCTCCCACCATGCCTCCTC-----GCCTTTGTGCCTCCTTTT
NM_001024860.1      GGAGCTGAACTGCAGGTTGCTCCCACCATGCCTCCTG-----GCCTTTGTGCCTCCTTTT
NM_214022.1         GGAGCTGAACTGTAGGTTGCTCCCACCTGGCCTCCTA-----GCCTCTGTGCCTCCTTTT
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         GGAGCTGAACAATAGGCTGTTCCCATGTAGCCCCCTG-----GCCTCTGTGCCTTCTTTT
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          ---TGTGTT-------TTT-----------------------------------------
NM_012675.3         TTTTCTTTTGCTTATGTTTAAAACAAGATATTTATCTAACCCAGTTGTCTTAATAATGCT
M13049.1            ------------------------------------------------------------
NM_001082263.1      ACTTATGTT-------TTTAAGA--AGATATTTATCTGATCAGGTTGTCTCACTAATGCT
NM_173966.3         GCTTATGTT-------TTTTAAA--AAATATTTATCTGATCGAGTTGTCTAAATGATGCT
NM_001024860.1      GCTTATGTT-------TTTTAAA--AAATATTTATGTGATCAAGTTGTCTAAATGATGCT
NM_214022.1         GCTTATGTT-------TTTAAAAACAAATATTTATCTGATCGAGTTGTCTAAATAATGCT
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         GATTATGTT-------TTTTAAA----ATATTTATCTGATTAAGTTGTCTAAACAATGCT
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          --TTTAATATGCAACTTGT-----------------------------------------
NM_012675.3         GATTTGGTGACCAGGCTGTCGCTACATCACTGAACCTCTGCTCCCCACGGGAGCCGTGAC
M13049.1            ------------------------------------------------------------
NM_001082263.1      GATTTGGTGACTGACCCGTCGCTACATCACCGAACCTCTGCTCCCTAAGGGAGTTGTGTT
NM_173966.3         GATTTGGTGACTGATTTGTCGCTACATCACTGAACCTCCGCTCCCCAGGGGAGTCATGCC
NM_001024860.1      GATTTGGTGACTGATTTGTCGCTACATCACTGAACCTCCGCTCCCCAGGGGAGTCATGCC
NM_214022.1         GATTTGGTGACTAACTTGTCGCTACATCGCTGAACCTCTGCTCCCCAGGGGAGTTGTGTC
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         GATTTGGTGACCAAC-TGTCACT-CATTGCTGAGCCTCTGCTCCCCAGGGGAGTTGTGTC
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          ------------------------------------------------------------
NM_012675.3         TGTAATCGCCCTACGGGTCATTGA-GAGAAATAAAGTTCGCTTGGAAAAGAAA-------
M13049.1            ------------------------------------------------------------
NM_001082263.1      GGTAACCGCCCTACTGGTCAGTGGCGAGAAATAAAGACTCCTTAAAAAAT----------
NM_173966.3         TGTAACCGCCCTACTGGTCAGTGGCGAGAAATAAAGTGTCCTGAGAAAAGAAAAAAAAAA
NM_001024860.1      TGTAACCGCCCTACTGGTCAGTGGCGAGAAATAAAGTGTCCTGAGAAAAGAAAAAAAAAA
NM_214022.1         TGTAACCGCCCTACTGGTCAGTGGCGAG--------------------------------
NM_001003244.4      ------------------------------------------------------------
NM_000594.4         TGTAATCGCCCTACTATTCAGTGGCGAGAAATAAAGTTTGCTTAGAAAAGAAA-------
NM_001081819.2      ------------------------------------------------------------
                                                                                

AJ417565.2          ------
NM_012675.3         ------
M13049.1            ------
NM_001082263.1      ------
NM_173966.3         AAAAAA
NM_001024860.1      AAAAA-
NM_214022.1         ------
NM_001003244.4      ------
NM_000594.4         ------
NM_001081819.2      ------
                          
